[package]
name = "vex-render"
description = "GPU rendering pipeline: wgpu, display lists, glyph/image atlas"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
vex-core = { path = "../vex-core" }
vex-css = { path = "../vex-css" }
vex-dom = { path = "../vex-dom" }
vex-layout = { path = "../vex-layout" }
wgpu.workspace = true
bytemuck.workspace = true
raw-window-handle.workspace = true
pollster.workspace = true
image.workspace = true
tracing.workspace = true
cosmic-text.workspace = true
log.workspace = true
