# Copyright (c) 2025 Vigo Browser. All rights reserved.
# Proprietary and confidential. Unauthorized copying prohibited.

import("//build/rust/rust_static_library.gni")

rust_static_library("vigo_filter_rs") {
  crate_name = "vigo_filter"
  crate_root = "//vigo/rust/vigo_filter/src/lib.rs"

  sources = [
    "//vigo/rust/vigo_filter/src/lib.rs",
  ]
}
