[package]
name = "vex-dom"
description = "DOM tree: arena-allocated nodes, traversal, events, selectors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
vex-core = { path = "../vex-core" }
smallvec.workspace = true
serde.workspace = true
selectors.workspace = true
cssparser.workspace = true
precomputed-hash = "0.1"
