# Copyright (c) 2025 Vigo Browser. All rights reserved.
# Proprietary and confidential. Unauthorized copying prohibited.

import("//vigo/build/config/vigo_buildflags.gni")

source_set("vigo_net") {
  sources = []
  deps = [
    "//base",
    "//content/public/browser",
    "//net",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
    "//url",
    "//vigo/build/config:vigo_buildflags",
  ]

  if (vigo_enable_adblock) {
    sources += [
      "vigo_adblock_throttle.cc",
      "vigo_adblock_throttle.h",
    ]
    deps += [ "//vigo/components/adblock" ]
  }

  if (vigo_enable_privacy_engine) {
    sources += [
      "vigo_privacy_throttle.cc",
      "vigo_privacy_throttle.h",
    ]
    deps += [ "//vigo/components/privacy_engine" ]
  }

  configs += [ "//vigo/build/config:vigo_config" ]
}

source_set("unit_tests") {
  testonly = true
  sources = []

  deps = [
    "//testing/gtest",
    "//url",
    "//vigo/build/config:vigo_buildflags",
  ]

  if (vigo_enable_adblock) {
    sources += [ "vigo_adblock_throttle_unittest.cc" ]
    deps += [ ":vigo_net" ]
  }

  if (vigo_enable_privacy_engine) {
    sources += [ "vigo_privacy_throttle_unittest.cc" ]
    deps += [
      ":vigo_net",
      "//vigo/components/privacy_engine",
    ]
  }
}
